### ISSUE TITLE
React Native module

### ISSUE THREAD

**Issue by brentvatne** [lokimeyburg/Stacker#10]
Hey @lokimeyburg! This library is really neat and I think it aligns really well with React Native - if implemented properly, users would not have to write a single line of native code to leverage this functionality. Just wanted to put that on your radar!

**Comment by lokimeyburg** [comment]
@brentvatne I'm watching React Native very closely - it's very rad! Haven't thought about creating a module - thanks for the idea - I'll definitely take a look.
