### ISSUE TITLE
Getting push setup

### ISSUE THREAD

**Issue by mikedev13** [lokimeyburg/Stacker#11]
Really love your project.  I’m stuck trying to get a link to push, then be able to navigate back to the first page.  For some reason it pushes to the link fine, but then navigation back from any link just goes to a blank page.  I specifically I tried the first page URL:
http://www.mike-forster.com/stackertest2/stest1?x_push_page=true
I can have any links from their, but when I navigate back, instead of going to the above URL, it just goes to a blank page.   Any help would be greatly appreciated!   I've attached several screenshots too.  Thanks.
![link selected example](https://cloud.githubusercontent.com/assets/3261114/8398831/573cf24e-1db3-11e5-84bf-0748aa2c177b.png)
![first page example](https://cloud.githubusercontent.com/assets/3261114/8398832/57434ffe-1db3-11e5-904d-c6a0e32aa5f1.png)
![back button pressed example](https://cloud.githubusercontent.com/assets/3261114/8398833/5745151e-1db3-11e5-8637-d04bccae9174.png)

**Comment by lokimeyburg** [comment]
Hey Mike, there are two ways to "go back". Either by going back one page (`x_pop_page=true`) or by going back to the very beginning (`x_clear_stack=true`). Note that I'm not "pushing" anything. So imagine I've pushed three pages on the stack and I'm currently on `/page 3`

```
/page1 => /page2 => /page 3
```

If I wanted to go back to `/page2` from a link I would do something like:

```
<a href="/page2?x_pop_page=true">Back</a>
```

Or if I wanted to go back to the start and reload the page you can try:

```
<a href="/page1?x_clear_stack_and_refresh=true">Cancel</a>
```

More here: http://www.lokimeyburg.com/Stacker/docs/url-structure/

**Comment by lokimeyburg** [comment]
@mikedev13 Let me know if you've got it working.

**Comment by mikedev13** [comment]
I don't have it working fully yet.  In iOS this is what I have:
AppDellegate.m
#import "LMStackerController.h"
@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {LMStackerController *myStackerController = [[LMStackerController alloc] initWithURL:@"http://www.mike-forster.com/spagetest1?x_page_title=Home"];
  self.window =[[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
  self.window.rootViewController = myStackerController;
  [self.window makeKeyAndVisible];
    return YES; }

-So that correctly loads what I would like as a first page, with the "Home" heading in the iOS navigation bar.  So it looks like the initial setup in iOS is correct.  What I still can't get working is when I click a link from the first page to another page like: (http://mike-forster.com/spagetest1/spagetest2/) I want to have the back button appear in the iOS navigation bar.  On the second page I added to the Back button:
<a href='http://www.mike-forster.com/spagetest1?x_pop_page=true">Back</a>
But the back button in the navigation bar in iOS isn't appearing.  Any thoughts?  I looked at the Ruby example, maybe I'm not declaring the pop=page=true in the class for the second page perhaps? Thanks.

**Comment by lokimeyburg** [comment]
@mikedev13 ... just to confirm, you've created a link on the home page (`spagetest1`) and it looks something like this?

```
<a href='/spagetest1/spagetest2/?x_push_page=true'>Next Page</a>
```

And it's _not_ going to the next page? It's just a white/blank page? 
Or is it that when you navigate back that it's a white page?

PS: Did you mean to cut off the last sentence?

**Comment by mikedev13** [comment]
Great, I figured it out. I was starting the app on page 1, and needed to declare in the link to page 2 the push page=true.  I was trying to have it in the back button already once the user has navigated to page 2.  I think this makes sense now. One more question.  If you were going to take an existing web site, and prepare it for a Stacker iOS app, what would be the best approach for declaring the URLs?  Go through each link and declare them all individually?  Or is there a more efficient approach?
THANKS!!!

**Comment by lokimeyburg** [comment]
I'm glad you got it working! As for your last point, the short answer is "yes you have to declare each url". The reason you have to go through each link/url individually is because you need to declare the title and buttons of the upcoming page. 

You could try to automate it with Javascript?

```
in HTML:
<a class="stacker-link" href="/mylink" data-title="My+Title">Visit Page</a>

in JS:
$("a.stacker").click(function(e){
  e.preventDefault();
  var title = $(this).attr("data-title");
  var href = $(this).attr("href");
  var queryString = "?x_push_page=true&x_page_title=";
  // now navigate to the constructed url
  window.location.href = href + queryString + title;
});
```
