### ISSUE TITLE
Load local HTML5 files

### ISSUE THREAD

**Issue by kas84** [lokimeyburg/Stacker#6]
Would be awesome if stacker could be able to load local HTML, CSS and JavaScript to avoid many requests.

**Comment by lokimeyburg** [comment]
Thanks @kas84! For reference for later, here's the discussion that started the issue: https://twitter.com/kas84/status/558204268273209344

```
"Local HTML files are certainly possible, just not in the immediate roadmap." - @lokimeyburg
```

**Comment by josephhsieh** [comment]
I assign [[NSBundle mainBundle] pathForResource:@"www/index" ofType:@"html"] as the URL string to the LMStackerController, and it works with local HTML5 files.

**Comment by lokimeyburg** [comment]
TIL :) This should get added to the docs

**Comment by kas84** [comment]
Cool!
